config/routes.rb
Rails.application.routes.draw do
  resources :pay_days

  resources :time_cards

  resources :calculate_pays

  resources :service_charges

  resources :sales_receipts

  resources :employees

end

app/models/time_card.rb
class TimeCard < ActiveRecord::Base
end

app/models/timecard.rb
class Timecard < ActiveRecord::Base
end

app/controllers/time_cards_controller.rb
class TimeCardsController < ApplicationController
  before_action :set_time_card, only: [:show, :edit, :update, :destroy]

  # GET /time_cards
  # GET /time_cards.json
  def index
    @time_cards = TimeCard.all
  end

  # GET /time_cards/1
  # GET /time_cards/1.json
  def show
  end

  # GET /time_cards/new
  def new
    @time_card = TimeCard.new
    @employees = Employee.all
  end

  # GET /time_cards/1/edit
  def edit
    @employees = Employee.all
  end

  # POST /time_cards
  # POST /time_cards.json
  def create
    @time_card = TimeCard.new(time_card_params)

    respond_to do |format|
      if @time_card.save
        format.html { redirect_to @time_card, notice: 'Time card was successfully created.' }
        format.json { render :show, status: :created, location: @time_card }
      else
        format.html { render :new }
        format.json { render json: @time_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /time_cards/1
  # PATCH/PUT /time_cards/1.json
  def update
    respond_to do |format|
      if @time_card.update(time_card_params)
        format.html { redirect_to @time_card, notice: 'Time card was successfully updated.' }
        format.json { render :show, status: :ok, location: @time_card }
      else
        format.html { render :edit }
        format.json { render json: @time_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /time_cards/1
  # DELETE /time_cards/1.json
  def destroy
    @time_card.destroy
    respond_to do |format|
      format.html { redirect_to time_cards_url, notice: 'Time card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_time_card
      @time_card = TimeCard.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def time_card_params
      params.require(:time_card).permit(:emp_id, :date, :time)
    end
end

app/controllers/timecards_controller.rb
class TimecardsController < ApplicationController
  before_action :set_timecard, only: [:show, :edit, :update, :destroy]

  # GET /timecards
  # GET /timecards.json
  def index
    @timecards = Timecard.all
  end

  # GET /timecards/1
  # GET /timecards/1.json
  def show
  end

  # GET /timecards/new
  def new
    @timecard = Timecard.new
    @employees = Employee.all
  end

  # GET /timecards/1/edit
  def edit
  end

  # POST /timecards
  # POST /timecards.json
  def create
    @timecard = Timecard.new(timecard_params)

    respond_to do |format|
      if @timecard.save
        format.html { redirect_to @timecard, notice: 'Timecard was successfully created.' }
        format.json { render :show, status: :created, location: @timecard }
      else
        format.html { render :new }
        format.json { render json: @timecard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /timecards/1
  # PATCH/PUT /timecards/1.json
  def update
    respond_to do |format|
      if @timecard.update(timecard_params)
        format.html { redirect_to @timecard, notice: 'Timecard was successfully updated.' }
        format.json { render :show, status: :ok, location: @timecard }
      else
        format.html { render :edit }
        format.json { render json: @timecard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /timecards/1
  # DELETE /timecards/1.json
  def destroy
    @timecard.destroy
    respond_to do |format|
      format.html { redirect_to timecards_url, notice: 'Timecard was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_timecard
      @timecard = Timecard.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def timecard_params
      params.require(:timecard).permit(:emp_id, :date, :time)
    end
end

app/helpers/time_cards_helper.rb
module TimeCardsHelper
end

app/helpers/timecards_helper.rb
module TimecardsHelper
end

app/views/time_cards/_form.html.erb
<%= simple_form_for(@time_card) do |f| %>
  <%= f.error_notification %>
  
  <div class="form-inputs">
    <div class="form-group select optional time_card_emp_id">
      <label class="select optional control-label" for="time_card_emp_id">Employees</label>
      <select class="select optional form-control" id="time_card_emp_id" name="time_card[emp_id]">
        <option value="">(사원번호) 이름을 선택하세요</option>
        
     <%# new에서 새로운 모델의 객체 @employees를 추가 후 받아옴 %>
        <% @employees.each do |employee| %>
          <% if employee.payment_type == 'hourly' %>
          <option value='<%=employee.emp_id %>'><%= '('+ employee.emp_id+ ')' +' '+ employee.name %></option>
          <% end %>
        <% end %>
        </select>
     </div>
     
    <%# date의 데이터형은 date, time의 데이터 형은integer%> 
    <%= f.input :date %>
    <%= f.input :time %>
  </div>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
  
  
<% end %>

app/views/time_cards/edit.html.erb
<h1>Editing time_card</h1>

<%= render 'form' %>

<%= link_to 'Show', @time_card %> |
<%= link_to 'Back', time_cards_path %>

app/views/time_cards/index.html.erb
<h1>Listing time_cards</h1>

<table>
  <thead>
    <tr>
      <th>Emp</th>
      <th>Time</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @time_cards.each do |time_card| %>
      <tr>
        <td><%= time_card.emp_id %></td>
        <td><%= time_card.time %></td>
        <td><%= time_card.date %></td>
        <td><%= link_to 'Show', time_card %></td>
        <td><%= link_to 'Edit', edit_time_card_path(time_card) %></td>
        <td><%= link_to 'Destroy', time_card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Time card', new_time_card_path %>

app/views/time_cards/new.html.erb
<h1>New time_card</h1>

<%= render 'form' %>

<%= link_to 'Back', time_cards_path %>

app/views/time_cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Emp:</strong>
  <%= @time_card.emp_id %>
</p>

<p>
  <strong>Date:</strong>
  <%= @time_card.date %>
</p>

<p>
  <strong>Time:</strong>
  <%= @time_card.time %>
</p>

<%= link_to 'Edit', edit_time_card_path(@time_card) %> |
<%= link_to 'Back', time_cards_path %>