config/routes.rb
Rails.application.routes.draw do
  resources :pay_days

  resources :time_cards

  resources :calculate_pays

  resources :service_charges

  resources :sales_receipts

  resources :employees

end

app/models/service_charge.rb
class ServiceCharge < ActiveRecord::Base
end

app/controllers/service_charges_controller.rb
class ServiceChargesController < ApplicationController
  before_action :set_service_charge, only: [:show, :edit, :update, :destroy]

  # GET /service_charges
  # GET /service_charges.json
  def index
    @service_charges = ServiceCharge.all
  end

  # GET /service_charges/1
  # GET /service_charges/1.json
  def show
  end

  # GET /service_charges/new
  def new
    @service_charge = ServiceCharge.new
    @employees = Employee.all
  end

  # GET /service_charges/1/edit
  def edit
    @employees = Employee.all
  end

  # POST /service_charges
  # POST /service_charges.json
  def create
    @service_charge = ServiceCharge.new(service_charge_params)

    respond_to do |format|
      if @service_charge.save
        format.html { redirect_to @service_charge, notice: 'Service charge was successfully created.' }
        format.json { render :show, status: :created, location: @service_charge }
      else
        format.html { render :new }
        format.json { render json: @service_charge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /service_charges/1
  # PATCH/PUT /service_charges/1.json
  def update
    respond_to do |format|
      if @service_charge.update(service_charge_params)
        format.html { redirect_to @service_charge, notice: 'Service charge was successfully updated.' }
        format.json { render :show, status: :ok, location: @service_charge }
      else
        format.html { render :edit }
        format.json { render json: @service_charge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /service_charges/1
  # DELETE /service_charges/1.json
  def destroy
    @service_charge.destroy
    respond_to do |format|
      format.html { redirect_to service_charges_url, notice: 'Service charge was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service_charge
      @service_charge = ServiceCharge.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_charge_params
      params.require(:service_charge).permit(:emp_id, :charge, :date)
    end
end

app/helpers/service_charges_helper.rb
module ServiceChargesHelper
end

app/views/service_charges/_form.html.erb
<%= simple_form_for(@service_charge) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <div class="form-group select optional service_charge_emp_id">
      <label class="select optional control-label" for="service_charge_emp_id">Employees</label>
      <select class="select optional form-control" id="service_charge_emp_id" name="service_charge[emp_id]">
        <option value="">(사원번호) 이름을 선택하세요</option>
        
     <%# new에서 새로운 모델의 객체 @employees를 추가 후 받아옴 %>
        <% @employees.each do |employee| %>
          <% if employee.Affiliation_type == 'unionAffiliation' %>
          <option value='<%=employee.emp_id %>'><%= '('+ employee.emp_id+ ')' +' '+ employee.name %></option>
          <% end %>
        <% end %>
        </select>
     </div>
   
    <%= f.input :charge %>
    <%= f.input :date %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/service_charges/edit.html.erb
<h1>Editing service_charge</h1>

<%= render 'form' %>

<%= link_to 'Show', @service_charge %> |
<%= link_to 'Back', service_charges_path %>

app/views/service_charges/index.html.erb
<h1>Listing service_charges</h1>

<table>
  <thead>
    <tr>
      <th>Emp</th>
      <th>Charge</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @service_charges.each do |service_charge| %>
      <tr>
        <td><%= service_charge.emp_id %></td>
        <td><%= service_charge.charge %></td>
        <td><%= service_charge.date %></td>
        <td><%= link_to 'Show', service_charge %></td>
        <td><%= link_to 'Edit', edit_service_charge_path(service_charge) %></td>
        <td><%= link_to 'Destroy', service_charge, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Service charge', new_service_charge_path %>

app/views/service_charges/new.html.erb
<h1>New service_charge</h1>

<%= render 'form' %>

<%= link_to 'Back', service_charges_path %>

app/views/service_charges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Emp:</strong>
  <%= @service_charge.emp_id %>
</p>

<p>
  <strong>Charge:</strong>
  <%= @service_charge.charge %>
</p>

<p>
  <strong>Date:</strong>
  <%= @service_charge.date %>
</p>

<%= link_to 'Edit', edit_service_charge_path(@service_charge) %> |
<%= link_to 'Back', service_charges_path %>